---
exclude:
  - '**/vendor/**/*'
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
  SelfClosingTag:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
